# Generated by Django 2.1.1 on 2018-10-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20181010_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(default='OPEN', max_length=10),
        ),
    ]
