# Generated by Django 2.1.1 on 2018-10-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='comment',
            field=models.CharField(max_length=300, verbose_name='Bid Comments'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='contact_details',
            field=models.CharField(max_length=300, verbose_name='Contact Details'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='price',
            field=models.IntegerField(verbose_name='Bid Price'),
        ),
        migrations.AlterField(
            model_name='post',
            name='budget',
            field=models.IntegerField(verbose_name='Maximum Budget'),
        ),
        migrations.AlterField(
            model_name='post',
            name='comment',
            field=models.CharField(max_length=300, verbose_name='Bid Comments'),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Post Title'),
        ),
    ]
