# Generated by Django 2.1.1 on 2018-10-25 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_auto_20181023_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='winning_bid',
            field=models.IntegerField(default=-1),
        ),
    ]
